version: '3'
services:
  mongo:
    image: mongo:3.2.20
    ports:
      - 27000:27000
    volumes:
      - ./data:/data/db
  php:
    # image: php:7.2-fpm
    build: ./php
    ports:
      - 9000:9000
    links:
      - mongo
    volumes:
      - ./blog:/blog
      - ./config/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:1.15.1
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ./blog:/blog
      - ./logs/nginx:/var/log/nginx
      - ./config/site.conf:/etc/nginx/conf.d/site.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
