version: '3'
services:
  mongo:
    image: mongo:3.2.20
    ports:
      - 27017:27017 
    volumes:
      - ./data:/data/db
  php:
    # container_name: elastic-php
    # image: php:7-fpm
    build: ./php
    ports:
      - 9000:9000

    volumes:
      - ./blog:/blog
      - ./config/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:1.15.1
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ./blog:/blog
      - ./logs/nginx:/var/log/nginx
      - ./config/site.conf:/etc/nginx/conf.d/site.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
    - elasticsearch